version: "3"

services:
  aluno-service:
    build: ./aluno-service
    depends_on:
      - discovery-server

  treino-service:
    build: ./treino-service
    depends_on:
      - discovery-server

  discovery-server:
    build:
      context: ./discovery-server/
    ports:
      - "8761:8761"

  gateway:
    build:
      context: ./gateway
    ports:
      - "8084:8084"
    depends_on:
      - discovery-server
