server:
    port: 8084
spring:
    application:
      name: gateway
    cloud:
        gateway:
            routes:
                - id: aluno
                  uri: lb://aluno
                  predicates:
                  - Path=/aluno/**
                - id: treino
                  uri: lb://treino
                  predicates:
                    - Path=/treino/**