server:
    port: 8084
spring:
    application:
      name: gateway
    cloud:
      gateway:
        routes:
          - id: aluno-service
            uri: lb://aluno-service
            predicates:
            - Path=/aluno/**
          - id: treino-service
            uri: lb://treino-service
            predicates:
              - Path=/treino/**